/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-09-06 16:23:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet-jstl-1.2.jar", Long.valueOf(1563360283983L));
    _jspx_dependants.put("/common/taglibs.jsp", Long.valueOf(1567501650326L));
    _jspx_dependants.put("jar:file:/E:/practice-jsp-servlet-jdbc/workspace%202/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GiaoDienJspServlet2/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("jar:file:/E:/practice-jsp-servlet-jdbc/workspace%202/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GiaoDienJspServlet2/WEB-INF/lib/javax.servlet-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1565624867589L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Admin page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\tDashboard <small>Statistics Overview</small>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><i class=\"fa fa-dashboard\"></i> Dashboard</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<div class=\"alert alert-success alert-dismissable\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">&times;</button>\r\n");
      out.write("\t\t\t\t\tWelcome to SB Admin by <a class=\"alert-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"http://startbootstrap.com\">Start Bootstrap</a>! Feel free to\r\n");
      out.write("\t\t\t\t\tuse this template for your admin needs! We are using a few\r\n");
      out.write("\t\t\t\t\tdifferent plugins to handle the dynamic tables and charts, so make\r\n");
      out.write("\t\t\t\t\tsure you check out the necessary documentation links provided.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-comments fa-5x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"announcement-heading\">456</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"announcement-text\">New Mentions!</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer announcement-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6\">View Mentions</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-arrow-circle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-warning\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-check fa-5x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"announcement-heading\">12</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"announcement-text\">To-Do Items</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer announcement-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6\">Complete Tasks</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-arrow-circle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-danger\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-tasks fa-5x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"announcement-heading\">18</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"announcement-text\">Crawl Errors</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer announcement-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6\">Fix Issues</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-arrow-circle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-success\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-comments fa-5x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"announcement-heading\">56</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"announcement-text\">New Orders!</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer announcement-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6\">Complete Orders</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-arrow-circle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-bar-chart-o\"></i> Traffic Statistics: October 1,\r\n");
      out.write("\t\t\t\t\t\t\t2013 - October 31, 2013\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"morris-chart-area\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-long-arrow-right\"></i> Traffic Sources: October\r\n");
      out.write("\t\t\t\t\t\t\t1, 2013 - October 31, 2013\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"morris-chart-donut\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">View Details <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i> Recent Activity\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"list-group-item\"> <span class=\"badge\">just\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnow</span> <i class=\"fa fa-calendar\"></i> Calendar updated\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\"> <span class=\"badge\">4\r\n");
      out.write("\t\t\t\t\t\t\t\t\tminutes ago</span> <i class=\"fa fa-comment\"></i> Commented on a post\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\"> <span class=\"badge\">23\r\n");
      out.write("\t\t\t\t\t\t\t\t\tminutes ago</span> <i class=\"fa fa-truck\"></i> Order 392 shipped\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\"> <span class=\"badge\">46\r\n");
      out.write("\t\t\t\t\t\t\t\t\tminutes ago</span> <i class=\"fa fa-money\"></i> Invoice 653 has been\r\n");
      out.write("\t\t\t\t\t\t\t\tpaid\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\"> <span class=\"badge\">1\r\n");
      out.write("\t\t\t\t\t\t\t\t\thour ago</span> <i class=\"fa fa-user\"></i> A new user has been added\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\"> <span class=\"badge\">2\r\n");
      out.write("\t\t\t\t\t\t\t\t\thours ago</span> <i class=\"fa fa-check\"></i> Completed task: \"pick up\r\n");
      out.write("\t\t\t\t\t\t\t\tdry cleaning\"\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\"> <span class=\"badge\">yesterday</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-globe\"></i> Saved the world\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\"> <span class=\"badge\">two\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdays ago</span> <i class=\"fa fa-check\"></i> Completed task: \"fix error\r\n");
      out.write("\t\t\t\t\t\t\t\ton sales page\"\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">View All Activity <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-money\"></i> Recent Transactions\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"table table-bordered table-hover table-striped tablesorter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Order # <i class=\"fa fa-sort\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Order Date <i class=\"fa fa-sort\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Order Time <i class=\"fa fa-sort\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Amount (USD) <i class=\"fa fa-sort\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3326</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>10/21/2013</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3:29 PM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$321.33</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3325</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>10/21/2013</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3:20 PM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$234.34</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3324</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>10/21/2013</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3:03 PM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$724.17</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3323</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>10/21/2013</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3:00 PM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$23.71</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3322</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>10/21/2013</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>2:49 PM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$8345.23</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3321</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>10/21/2013</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>2:23 PM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$245.12</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3320</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>10/21/2013</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>2:15 PM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$5663.54</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>3319</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>10/21/2013</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>2:13 PM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$943.45</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">View All Transactions <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /#page-wrapper -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
